name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ilgianlu/tagyou:latest
          ilgianlu/tagyou:${{ github.ref_name }}
          ilgianlu/tagyou:${{ github.ref_name }}-${{ github.sha }}

  build-arm:

    runs-on: ubuntu-latest
    env:      
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm64/v8
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64
        file: ./Dockerfile
        push: true
        build-args: GOARCH=arm64v8
        tags: |
          ilgianlu/tagyou:arm
          ilgianlu/tagyou:arm-latest
          ilgianlu/tagyou:arm-${{ github.ref_name }}
          ilgianlu/tagyou:arm-${{ github.ref_name }}-${{ github.sha }}
